import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div
      style={{
        height: '100vh',
        display: 'flex',
        flexDirection: 'column',
        gap: '50px',
        justifyContent: 'center',
        alignItems: 'center',
      }}
    >
      <Head>
        <title>Διπλωματικές Μετσόβιου Πολυτεχνείου</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='center_items'>
        <h1 style={{ fontSize: '3rem' }}>
          Εδώ θα γίνεται το log in μέσω του Συστήματος του Πολυτεχνείου{' '}
        </h1>
      </div>
      <Link href={'/teacher'} passHref={true}>
        <button
          style={{
            width: '200px',
            height: '50px',
            border: '1px solid black',
            borderRadius: '5px',
          }}
        >
          Καθηγητής
        </button>
      </Link>
      <Link href={'/student'} passHref={true}>
        <button
          style={{
            width: '200px',
            height: '50px',
            border: '1px solid black',
            borderRadius: '5px',
          }}
        >
          Φοιτητής
        </button>
      </Link>
    </div>
  )
}
