import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Διπλωματικές Μετσόβιου Πολυτεχνείου</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='center_items' style={{ height: '100vh' }}>
        <h1 style={{ fontSize: '3rem' }}>
          Εδώ θα γίνεται το log in μέσω του Συστήματος του Πολυτεχνείου{' '}
        </h1>
      </div>
    </div>
  )
}
