import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Theseus</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>This is the Log in page</h1>
    </div>
  )
}
